language: python
python:
    - "3.4"
install: python3 -m pip install -r requirements.txt
env:
    - CONFIG_PATH=bulletJournal.config.TravisConfig
before_script:
    - psql -c 'create database "bulletJournal-test";' -U postgres
script:
    - PYTHONPATH=. python3 tests/bulletJournal_tests.py
    - PYTHONPATH=. python3 tests/test_views_acceptance.py