language: python
python:
    - "3.4"
install: python -m pip install -r requirements.txt
env:
    - CONFIG_PATH=bulletJournal.config.TravisConfig
before_script:
    - psql -c 'create database "bulletJournal-test";' -U postgres
script:
    - PYTHONPATH=. python tests/test_views_integration.py
    - PYTHONPATH=. python tests/test_views_acceptance.py